<?php

use Illuminate\Database\Seeder;
use App\Parametro;

class ParametroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Parametro::truncate();

        // Departamentos
        DB::insert("
            INSERT INTO `parametros` (`nombre`, `tipo`) VALUES
            ('Amazonas', 1),
            ('Antioquia', 1),
            ('Arauca', 1),
            ('Atlántico', 1),
            ('Bolívar', 1),
            ('Boyacá', 1),
            ('Caldas', 1),
            ('Caquetá', 1),
            ('Casanare', 1),
            ('Cauca', 1),
            ('Cesar', 1),
            ('Chocó', 1),
            ('Córdoba', 1),
            ('Cundinamarca', 1),
            ('Guainía', 1),
            ('Guaviare', 1),
            ('Huila', 1),
            ('La Guajira', 1),
            ('Magdalena', 1),
            ('Meta', 1),
            ('Nariño', 1),
            ('Norte de Santander', 1),
            ('Putumayo', 1),
            ('Quindío', 1),
            ('Risaralda', 1),
            ('San Andrés y Providencia', 1),
            ('Santander', 1),
            ('Sucre', 1),
            ('Tolima', 1),
            ('Valle del Cauca', 1),
            ('Vaupés', 1),
            ('Vichada', 1)
        ");

        // Municipios
        DB::insert("
            INSERT INTO `parametros` (`nombre`, `tipo`) VALUES
            ('Medellín',2),
            ('Abejorral',2),
            ('Abriaquí',2),
            ('Alejandría',2),
            ('Amagá',2),
            ('Amalfi',2),
            ('Andes',2),
            ('Angelópolis',2),
            ('Angostura',2),
            ('Anorí',2),
            ('Chimá',2),
            ('Anza',2),
            ('Apartadó',2),
            ('Arboletes',2),
            ('Argelia',2),
            ('Armenia',2),
            ('Barbosa',2),
            ('Bello',2),
            ('Betania',2),
            ('Betulia',2),
            ('Ciudad Bolívar',2),
            ('Briceño',2),
            ('Buriticá',2),
            ('Cáceres',2),
            ('Caicedo',2),
            ('Caldas',2),
            ('Campamento',2),
            ('Cañasgordas',2),
            ('Caracolí',2),
            ('Caramanta',2),
            ('Carepa',2),
            ('Sampués',2),
            ('Carolina',2),
            ('Caucasia',2),
            ('Chigorodó',2),
            ('Cisneros',2),
            ('Cocorná',2),
            ('Concepción',2),
            ('Concordia',2),
            ('Copacabana',2),
            ('Dabeiba',2),
            ('Don Matías',2),
            ('Ebéjico',2),
            ('El Bagre',2),
            ('Entrerrios',2),
            ('Envigado',2),
            ('Fredonia',2),
            ('Giraldo',2),
            ('Girardota',2),
            ('Gómez Plata',2),
            ('Nunchía',2),
            ('Guadalupe',2),
            ('Guarne',2),
            ('Guatapé',2),
            ('Heliconia',2),
            ('Hispania',2),
            ('Itagui',2),
            ('Ituango',2),
            ('Pamplona',2),
            ('Jericó',2),
            ('La Ceja',2),
            ('La Estrella',2),
            ('La Pintada',2),
            ('La Unión',2),
            ('Liborina',2),
            ('Maceo',2),
            ('Marinilla',2),
            ('Montebello',2),
            ('Murindó',2),
            ('Mutatá',2),
            ('Nariño',2),
            ('Necoclí',2),
            ('Nechí',2),
            ('Olaya',2),
            ('Peñol',2),
            ('Peque',2),
            ('Pueblorrico',2),
            ('Puerto Berrío',2),
            ('Puerto Nare',2),
            ('Puerto Triunfo',2),
            ('Remedios',2),
            ('Retiro',2),
            ('Rionegro',2),
            ('Sabanalarga',2),
            ('Sabaneta',2),
            ('Salgar',2),
            ('Albán',2),
            ('Yavaraté',2),
            ('San Francisco',2),
            ('San Jerónimo',2),
            ('Montelíbano',2),
            ('Puerto Asís',2),
            ('San Luis',2),
            ('San Pedro',2),
            ('Corozal',2),
            ('San Rafael',2),
            ('San Roque',2),
            ('San Vicente',2),
            ('Santa Bárbara',2),
            ('Buesaco',2),
            ('Santo Domingo',2),
            ('El Santuario',2),
            ('Segovia',2),
            ('Sopetrán',2),
            ('Támesis',2),
            ('Tarazá',2),
            ('Tarso',2),
            ('Titiribí',2),
            ('Toledo',2),
            ('Turbo',2),
            ('Uramita',2),
            ('Urrao',2),
            ('Valdivia',2),
            ('Valparaíso',2),
            ('Vegachí',2),
            ('Venecia',2),
            ('Maní',2),
            ('Yalí',2),
            ('Yarumal',2),
            ('Yolombó',2),
            ('Yondó',2),
            ('Zaragoza',2),
            ('Barranquilla',2),
            ('Baranoa',2),
            ('El Peñón',2),
            ('Candelaria',2),
            ('Galapa',2),
            ('Tuluá',2),
            ('Casabianca',2),
            ('Luruaco',2),
            ('Malambo',2),
            ('Manatí',2),
            ('Anolaima',2),
            ('Piojó',2),
            ('Polonuevo',2),
            ('Chía',2),
            ('San Andrés de Tumaco',2),
            ('Sabanagrande',2),
            ('Sabanalarga',2),
            ('Santa Lucía',2),
            ('Santo Tomás',2),
            ('Soledad',2),
            ('Suan',2),
            ('Tubará',2),
            ('Usiacurí',2),
            ('Milán',2),
            ('Capitanejo',2),
            ('Achí',2),
            ('Anzoátegui',2),
            ('Arenal',2),
            ('Arjona',2),
            ('Arroyohondo',2),
            ('Florida',2),
            ('Calamar',2),
            ('Cantagallo',2),
            ('Cicuco',2),
            ('Córdoba',2),
            ('Clemencia',2),
            ('Repelón',2),
            ('El Guamo',2),
            ('Frontino',2),
            ('Magangué',2),
            ('Mahates',2),
            ('Margarita',2),
            ('Montecristo',2),
            ('Mompós',2),
            ('Morales',2),
            ('Norosí',2),
            ('Pinillos',2),
            ('Regidor',2),
            ('Río Viejo',2),
            ('San Estanislao',2),
            ('San Fernando',2),
            ('El Peñón',2),
            ('Pamplonita',2),
            ('San Juan Nepomuceno',2),
            ('Miriti Paraná',2),
            ('Támara',2),
            ('Santa Catalina',2),
            ('Santa Rosa',2),
            ('Tibasosa',2),
            ('Simití',2),
            ('Soplaviento',2),
            ('Talaigua Nuevo',2),
            ('Tiquisio',2),
            ('Turbaco',2),
            ('Turbaná',2),
            ('Villanueva',2),
            ('Páez',2),
            ('Tunja',2),
            ('Almeida',2),
            ('Aquitania',2),
            ('Arcabuco',2),
            ('Ibagué',2),
            ('Berbeo',2),
            ('Betéitiva',2),
            ('Boavita',2),
            ('Boyacá',2),
            ('Briceño',2),
            ('Buena Vista',2),
            ('Busbanzá',2),
            ('Caldas',2),
            ('Campohermoso',2),
            ('Cerinza',2),
            ('Chinavita',2),
            ('Chiquinquirá',2),
            ('Chiscas',2),
            ('Chita',2),
            ('Chitaraque',2),
            ('Chivatá',2),
            ('Cómbita',2),
            ('Coper',2),
            ('Corrales',2),
            ('Covarachía',2),
            ('Cubará',2),
            ('Cucaita',2),
            ('Cuítiva',2),
            ('Chíquiza',2),
            ('Chivor',2),
            ('Duitama',2),
            ('El Cocuy',2),
            ('El Espino',2),
            ('Firavitoba',2),
            ('Floresta',2),
            ('Gachantivá',2),
            ('Gameza',2),
            ('Garagoa',2),
            ('Guacamayas',2),
            ('Guateque',2),
            ('Guayatá',2),
            ('Güicán',2),
            ('Iza',2),
            ('Jenesano',2),
            ('Jericó',2),
            ('Labranzagrande',2),
            ('La Capilla',2),
            ('La Victoria',2),
            ('Puerto Colombia',2),
            ('Belén',2),
            ('Macanal',2),
            ('Maripí',2),
            ('Miraflores',2),
            ('Mongua',2),
            ('Monguí',2),
            ('Moniquirá',2),
            ('Muzo',2),
            ('Nobsa',2),
            ('Nuevo Colón',2),
            ('Oicatá',2),
            ('Otanche',2),
            ('Pachavita',2),
            ('Páez',2),
            ('Paipa',2),
            ('Pajarito',2),
            ('Panqueba',2),
            ('Pauna',2),
            ('Paya',2),
            ('Sopó',2),
            ('Pesca',2),
            ('Pisba',2),
            ('Puerto Boyacá',2),
            ('Quípama',2),
            ('Ramiriquí',2),
            ('Ráquira',2),
            ('Rondón',2),
            ('Saboyá',2),
            ('Sáchica',2),
            ('Samacá',2),
            ('San Eduardo',2),
            ('Carmen del Darien',2),
            ('Gama',2),
            ('San Mateo',2),
            ('Sasaima',2),
            ('Chachagüí',2),
            ('Santana',2),
            ('Santa María',2),
            ('Cúcuta',2),
            ('Santa Sofía',2),
            ('Sativanorte',2),
            ('Sativasur',2),
            ('Siachoque',2),
            ('Soatá',2),
            ('Socotá',2),
            ('Socha',2),
            ('Sogamoso',2),
            ('Somondoco',2),
            ('Sora',2),
            ('Sotaquirá',2),
            ('Soracá',2),
            ('Susacón',2),
            ('Sutamarchán',2),
            ('Sutatenza',2),
            ('Tasco',2),
            ('Tenza',2),
            ('Tibaná',2),
            ('Tinjacá',2),
            ('Tipacoque',2),
            ('Toca',2),
            ('Cartagena',2),
            ('Tópaga',2),
            ('Tota',2),
            ('Turmequé',2),
            ('Granada',2),
            ('Tutazá',2),
            ('Umbita',2),
            ('Ventaquemada',2),
            ('Viracachá',2),
            ('Zetaquira',2),
            ('Manizales',2),
            ('Aguadas',2),
            ('Anserma',2),
            ('Aranzazu',2),
            ('Belalcázar',2),
            ('Chinchiná',2),
            ('Filadelfia',2),
            ('La Dorada',2),
            ('La Merced',2),
            ('Manzanares',2),
            ('Marmato',2),
            ('Marulanda',2),
            ('Neira',2),
            ('Norcasia',2),
            ('Pácora',2),
            ('Palestina',2),
            ('Pensilvania',2),
            ('Riosucio',2),
            ('Risaralda',2),
            ('Salamina',2),
            ('Samaná',2),
            ('San José',2),
            ('Supía',2),
            ('Victoria',2),
            ('Villamaría',2),
            ('Viterbo',2),
            ('Florencia',2),
            ('Albania',2),
            ('Santa Bárbara de Pinto',2),
            ('María la Baja',2),
            ('Curillo',2),
            ('El Doncello',2),
            ('El Paujil',2),
            ('Morelia',2),
            ('Puerto Rico',2),
            ('La Montañita',2),
            ('San Vicente del Caguán',2),
            ('Solano',2),
            ('Solita',2),
            ('Valparaíso',2),
            ('Popayán',2),
            ('Almaguer',2),
            ('Argelia',2),
            ('Balboa',2),
            ('Bolívar',2),
            ('Buenos Aires',2),
            ('Cajibío',2),
            ('Caldono',2),
            ('Caloto',2),
            ('Corinto',2),
            ('El Tambo',2),
            ('Florencia',2),
            ('Guachené',2),
            ('Guapi',2),
            ('Inzá',2),
            ('Jambaló',2),
            ('La Sierra',2),
            ('La Vega',2),
            ('López',2),
            ('Mercaderes',2),
            ('Miranda',2),
            ('Morales',2),
            ('Padilla',2),
            ('Patía',2),
            ('Piamonte',2),
            ('Piendamó',2),
            ('Puerto Tejada',2),
            ('Puracé',2),
            ('Rosas',2),
            ('El Peñón',2),
            ('Jardín',2),
            ('Santa Rosa',2),
            ('Silvia',2),
            ('Sotara',2),
            ('Suárez',2),
            ('Sucre',2),
            ('Timbío',2),
            ('Timbiquí',2),
            ('Toribio',2),
            ('Totoró',2),
            ('Villa Rica',2),
            ('Valledupar',2),
            ('Aguachica',2),
            ('Agustín Codazzi',2),
            ('Astrea',2),
            ('Becerril',2),
            ('Bosconia',2),
            ('Chimichagua',2),
            ('Chiriguaná',2),
            ('Curumaní',2),
            ('El Copey',2),
            ('El Paso',2),
            ('Gamarra',2),
            ('González',2),
            ('La Gloria',2),
            ('Jamundí',2),
            ('Manaure',2),
            ('Pailitas',2),
            ('Pelaya',2),
            ('Pueblo Bello',2),
            ('Tadó',2),
            ('La Paz',2),
            ('San Alberto',2),
            ('San Diego',2),
            ('San Martín',2),
            ('Tamalameque',2),
            ('Montería',2),
            ('Ayapel',2),
            ('Buenavista',2),
            ('Canalete',2),
            ('Cereté',2),
            ('Chimá',2),
            ('Chinú',2),
            ('Orocué',2),
            ('Cotorra',2),
            ('Líbano',2),
            ('Lorica',2),
            ('Los Córdobas',2),
            ('Momil',2),
            ('Moñitos',2),
            ('Planeta Rica',2),
            ('Pueblo Nuevo',2),
            ('Puerto Escondido',2),
            ('Yacopí',2),
            ('Purísima',2),
            ('Sahagún',2),
            ('San Andrés Sotavento',2),
            ('San Antero',2),
            ('Calarcá',2),
            ('Sonsón',2),
            ('El Carmen',2),
            ('San Pelayo',2),
            ('Tierralta',2),
            ('Tuchín',2),
            ('Valencia',2),
            ('Lérida',2),
            ('Anapoima',2),
            ('Arbeláez',2),
            ('Beltrán',2),
            ('Bituima',2),
            ('Bojacá',2),
            ('Cabrera',2),
            ('Cachipay',2),
            ('Cajicá',2),
            ('Caparrapí',2),
            ('Caqueza',2),
            ('La Apartada',2),
            ('Chaguaní',2),
            ('Chipaque',2),
            ('Choachí',2),
            ('Chocontá',2),
            ('Cogua',2),
            ('Cota',2),
            ('Cucunubá',2),
            ('El Colegio',2),
            ('El Rosal',2),
            ('Fomeque',2),
            ('Fosca',2),
            ('Funza',2),
            ('Fúquene',2),
            ('Gachala',2),
            ('Gachancipá',2),
            ('Gachetá',2),
            ('San Cristóbal',2),
            ('Girardot',2),
            ('Granada',2),
            ('Guachetá',2),
            ('Guaduas',2),
            ('Guasca',2),
            ('Guataquí',2),
            ('Guatavita',2),
            ('Fusagasugá',2),
            ('Guayabetal',2),
            ('Gutiérrez',2),
            ('Jerusalén',2),
            ('Junín',2),
            ('La Calera',2),
            ('La Mesa',2),
            ('La Palma',2),
            ('La Peña',2),
            ('La Vega',2),
            ('Lenguazaque',2),
            ('Macheta',2),
            ('Madrid',2),
            ('Manta',2),
            ('Medina',2),
            ('Mosquera',2),
            ('Nariño',2),
            ('Nemocón',2),
            ('Nilo',2),
            ('Nimaima',2),
            ('Nocaima',2),
            ('Venecia',2),
            ('Pacho',2),
            ('Paime',2),
            ('Pandi',2),
            ('Paratebueno',2),
            ('Pasca',2),
            ('Puerto Salgar',2),
            ('Pulí',2),
            ('Quebradanegra',2),
            ('Quetame',2),
            ('Quipile',2),
            ('Apulo',2),
            ('Ricaurte',2),
            ('Zambrano',2),
            ('San Bernardo',2),
            ('San Cayetano',2),
            ('San Francisco',2),
            ('La Uvita',2),
            ('Zipaquirá',2),
            ('Sesquilé',2),
            ('Sibaté',2),
            ('Silvania',2),
            ('Simijaca',2),
            ('Soacha',2),
            ('Subachoque',2),
            ('Suesca',2),
            ('Supatá',2),
            ('Susa',2),
            ('Sutatausa',2),
            ('Tabio',2),
            ('Génova',2),
            ('Tausa',2),
            ('Tena',2),
            ('Tenjo',2),
            ('Tibacuy',2),
            ('Tibirita',2),
            ('Tocaima',2),
            ('Tocancipá',2),
            ('Topaipí',2),
            ('Ubalá',2),
            ('Ubaque',2),
            ('Suárez',2),
            ('Une',2),
            ('Útica',2),
            ('Castilla la Nueva',2),
            ('Vianí',2),
            ('Villagómez',2),
            ('Villapinzón',2),
            ('Villeta',2),
            ('Viotá',2),
            ('Zipacón',2),
            ('Quibdó',2),
            ('Acandí',2),
            ('Alto Baudo',2),
            ('Atrato',2),
            ('Bagadó',2),
            ('Bahía Solano',2),
            ('Bajo Baudó',2),
            ('Belén',2),
            ('Bojaya',2),
            ('Unión Panamericana',2),
            ('Pueblo Viejo',2),
            ('Cértegui',2),
            ('Condoto',2),
            ('Villagarzón',2),
            ('Facatativá',2),
            ('Juradó',2),
            ('Lloró',2),
            ('Medio Atrato',2),
            ('Medio Baudó',2),
            ('Medio San Juan',2),
            ('Nóvita',2),
            ('Nuquí',2),
            ('Río Iro',2),
            ('Río Quito',2),
            ('Riosucio',2),
            ('Puerto Libertador',2),
            ('Sipí',2),
            ('Unguía',2),
            ('Neiva',2),
            ('Acevedo',2),
            ('Agrado',2),
            ('Aipe',2),
            ('Algeciras',2),
            ('Altamira',2),
            ('Baraya',2),
            ('Campoalegre',2),
            ('Colombia',2),
            ('Elías',2),
            ('Garzón',2),
            ('Gigante',2),
            ('Guadalupe',2),
            ('Hobo',2),
            ('Iquira',2),
            ('Isnos',2),
            ('La Argentina',2),
            ('La Plata',2),
            ('Marquetalia',2),
            ('Nátaga',2),
            ('Oporapa',2),
            ('Paicol',2),
            ('Palermo',2),
            ('Palestina',2),
            ('Pital',2),
            ('Pitalito',2),
            ('Rivera',2),
            ('Saladoblanco',2),
            ('Arboleda',2),
            ('Santa María',2),
            ('Suaza',2),
            ('Tarqui',2),
            ('Tesalia',2),
            ('Tello',2),
            ('Teruel',2),
            ('Timaná',2),
            ('Villavieja',2),
            ('Yaguará',2),
            ('Riohacha',2),
            ('Albania',2),
            ('Barrancas',2),
            ('Dibula',2),
            ('Distracción',2),
            ('El Molino',2),
            ('Fonseca',2),
            ('Hatonuevo',2),
            ('Maicao',2),
            ('Manaure',2),
            ('Uribia',2),
            ('Urumita',2),
            ('Villanueva',2),
            ('Santa Marta',2),
            ('Algarrobo',2),
            ('Aracataca',2),
            ('Ariguaní',2),
            ('Cerro San Antonio',2),
            ('Chivolo',2),
            ('Concordia',2),
            ('El Banco',2),
            ('El Piñon',2),
            ('El Retén',2),
            ('Fundación',2),
            ('Guamal',2),
            ('Nueva Granada',2),
            ('Pedraza',2),
            ('Pivijay',2),
            ('Plato',2),
            ('Remolino',2),
            ('Salamina',2),
            ('San Zenón',2),
            ('Santa Ana',2),
            ('Sitionuevo',2),
            ('Tenerife',2),
            ('Zapayán',2),
            ('Zona Bananera',2),
            ('Villavicencio',2),
            ('Acacias',2),
            ('Cabuyaro',2),
            ('Cubarral',2),
            ('Cumaral',2),
            ('El Calvario',2),
            ('El Castillo',2),
            ('El Dorado',2),
            ('Buenaventura',2),
            ('Granada',2),
            ('Guamal',2),
            ('Mapiripán',2),
            ('Mesetas',2),
            ('La Macarena',2),
            ('Uribe',2),
            ('Lejanías',2),
            ('Puerto Concordia',2),
            ('Puerto Gaitán',2),
            ('Puerto López',2),
            ('Puerto Lleras',2),
            ('Puerto Rico',2),
            ('Restrepo',2),
            ('Ciénaga',2),
            ('Ponedera',2),
            ('San Juanito',2),
            ('San Martín',2),
            ('Vista Hermosa',2),
            ('Pasto',2),
            ('Albán',2),
            ('Aldana',2),
            ('Ancuyá',2),
            ('Tununguá',2),
            ('Barbacoas',2),
            ('Motavita',2),
            ('San Bernardo del Viento',2),
            ('Colón',2),
            ('Consaca',2),
            ('Contadero',2),
            ('Córdoba',2),
            ('Cuaspud',2),
            ('Cumbal',2),
            ('Cumbitara',2),
            ('El Charco',2),
            ('El Peñol',2),
            ('El Rosario',2),
            ('Istmina',2),
            ('El Tambo',2),
            ('Funes',2),
            ('Guachucal',2),
            ('Guaitarilla',2),
            ('Gualmatán',2),
            ('Iles',2),
            ('Imués',2),
            ('Ipiales',2),
            ('La Cruz',2),
            ('La Florida',2),
            ('La Llanada',2),
            ('La Tola',2),
            ('La Unión',2),
            ('Leiva',2),
            ('Linares',2),
            ('Los Andes',2),
            ('Magüí',2),
            ('Mallama',2),
            ('Mosquera',2),
            ('Nariño',2),
            ('Olaya Herrera',2),
            ('Ospina',2),
            ('Francisco Pizarro',2),
            ('Policarpa',2),
            ('Potosí',2),
            ('Providencia',2),
            ('Puerres',2),
            ('Pupiales',2),
            ('Ricaurte',2),
            ('Roberto Payán',2),
            ('Samaniego',2),
            ('Sandoná',2),
            ('San Bernardo',2),
            ('San Lorenzo',2),
            ('San Pablo',2),
            ('Belmira',2),
            ('Ciénega',2),
            ('Santa Bárbara',2),
            ('Sapuyes',2),
            ('Taminango',2),
            ('Tangua',2),
            ('Santacruz',2),
            ('Túquerres',2),
            ('Yacuanquer',2),
            ('Puerto Wilches',2),
            ('Puerto Parra',2),
            ('Armenia',2),
            ('Buenavista',2),
            ('Circasia',2),
            ('Córdoba',2),
            ('Filandia',2),
            ('La Tebaida',2),
            ('Montenegro',2),
            ('Pijao',2),
            ('Quimbaya',2),
            ('Salento',2),
            ('Pereira',2),
            ('Apía',2),
            ('Balboa',2),
            ('Dosquebradas',2),
            ('Guática',2),
            ('La Celia',2),
            ('La Virginia',2),
            ('Marsella',2),
            ('Mistrató',2),
            ('Pueblo Rico',2),
            ('Quinchía',2),
            ('Santuario',2),
            ('Bucaramanga',2),
            ('Aguada',2),
            ('Albania',2),
            ('Aratoca',2),
            ('Barbosa',2),
            ('Barichara',2),
            ('Barrancabermeja',2),
            ('Betulia',2),
            ('Bolívar',2),
            ('Cabrera',2),
            ('California',2),
            ('Carcasí',2),
            ('Cepitá',2),
            ('Cerrito',2),
            ('Charalá',2),
            ('Charta',2),
            ('Chipatá',2),
            ('Cimitarra',2),
            ('Concepción',2),
            ('Confines',2),
            ('Contratación',2),
            ('Coromoro',2),
            ('Curití',2),
            ('El Guacamayo',2),
            ('El Playón',2),
            ('Encino',2),
            ('Enciso',2),
            ('Florián',2),
            ('Floridablanca',2),
            ('Galán',2),
            ('Gambita',2),
            ('Girón',2),
            ('Guaca',2),
            ('Guadalupe',2),
            ('Guapotá',2),
            ('Guavatá',2),
            ('Güepsa',2),
            ('Jesús María',2),
            ('Jordán',2),
            ('La Belleza',2),
            ('Landázuri',2),
            ('La Paz',2),
            ('Lebríja',2),
            ('Los Santos',2),
            ('Macaravita',2),
            ('Málaga',2),
            ('Matanza',2),
            ('Mogotes',2),
            ('Molagavita',2),
            ('Ocamonte',2),
            ('Oiba',2),
            ('Onzaga',2),
            ('Palmar',2),
            ('Páramo',2),
            ('Piedecuesta',2),
            ('Pinchote',2),
            ('Puente Nacional',2),
            ('Rionegro',2),
            ('San Andrés',2),
            ('San Gil',2),
            ('San Joaquín',2),
            ('San Miguel',2),
            ('Santa Bárbara',2),
            ('Simacota',2),
            ('Socorro',2),
            ('Suaita',2),
            ('Sucre',2),
            ('Suratá',2),
            ('Tona',2),
            ('Vélez',2),
            ('Vetas',2),
            ('Villanueva',2),
            ('Zapatoca',2),
            ('Sincelejo',2),
            ('Buenavista',2),
            ('Caimito',2),
            ('Coloso',2),
            ('Coveñas',2),
            ('Chalán',2),
            ('El Roble',2),
            ('Galeras',2),
            ('Guaranda',2),
            ('La Unión',2),
            ('Los Palmitos',2),
            ('Majagual',2),
            ('Morroa',2),
            ('Ovejas',2),
            ('Palmito',2),
            ('San Benito Abad',2),
            ('San Marcos',2),
            ('San Onofre',2),
            ('San Pedro',2),
            ('Sucre',2),
            ('Tolú Viejo',2),
            ('Alpujarra',2),
            ('Alvarado',2),
            ('Ambalema',2),
            ('Armero',2),
            ('Ataco',2),
            ('Cajamarca',2),
            ('Chaparral',2),
            ('Coello',2),
            ('Coyaima',2),
            ('Cunday',2),
            ('Dolores',2),
            ('Espinal',2),
            ('Falan',2),
            ('Flandes',2),
            ('Fresno',2),
            ('Guamo',2),
            ('Herveo',2),
            ('Honda',2),
            ('Icononzo',2),
            ('Mariquita',2),
            ('Melgar',2),
            ('Murillo',2),
            ('Natagaima',2),
            ('Ortega',2),
            ('Palocabildo',2),
            ('Piedras',2),
            ('Planadas',2),
            ('Prado',2),
            ('Purificación',2),
            ('Rio Blanco',2),
            ('Roncesvalles',2),
            ('Rovira',2),
            ('Saldaña',2),
            ('Santa Isabel',2),
            ('Venadillo',2),
            ('Villahermosa',2),
            ('Villarrica',2),
            ('Arauquita',2),
            ('Cravo Norte',2),
            ('Fortul',2),
            ('Puerto Rondón',2),
            ('Saravena',2),
            ('Tame',2),
            ('Arauca',2),
            ('Yopal',2),
            ('Aguazul',2),
            ('Chámeza',2),
            ('Hato Corozal',2),
            ('La Salina',2),
            ('Monterrey',2),
            ('Pore',2),
            ('Recetor',2),
            ('Sabanalarga',2),
            ('Sácama',2),
            ('Tauramena',2),
            ('Trinidad',2),
            ('Villanueva',2),
            ('Mocoa',2),
            ('Colón',2),
            ('Orito',2),
            ('Puerto Caicedo',2),
            ('Puerto Guzmán',2),
            ('Leguízamo',2),
            ('Sibundoy',2),
            ('San Francisco',2),
            ('San Miguel',2),
            ('Santiago',2),
            ('Leticia',2),
            ('El Encanto',2),
            ('La Chorrera',2),
            ('La Pedrera',2),
            ('La Victoria',2),
            ('Puerto Arica',2),
            ('Puerto Nariño',2),
            ('Puerto Santander',2),
            ('Tarapacá',2),
            ('Inírida',2),
            ('Barranco Minas',2),
            ('Mapiripana',2),
            ('San Felipe',2),
            ('Puerto Colombia',2),
            ('La Guadalupe',2),
            ('Cacahual',2),
            ('Pana Pana',2),
            ('Morichal',2),
            ('Mitú',2),
            ('Caruru',2),
            ('Pacoa',2),
            ('Taraira',2),
            ('Papunaua',2),
            ('Puerto Carreño',2),
            ('La Primavera',2),
            ('Santa Rosalía',2),
            ('Cumaribo',2),
            ('San José del Fragua',2),
            ('Barranca de Upía',2),
            ('Palmas del Socorro',2),
            ('San Juan de Río Seco',2),
            ('Juan de Acosta',2),
            ('Fuente de Oro',2),
            ('San Luis de Gaceno',2),
            ('El Litoral del San Juan',2),
            ('Villa de San Diego de Ubate',2),
            ('Barranco de Loba',2),
            ('Togüí',2),
            ('Santa Rosa del Sur',2),
            ('El Cantón del San Pablo',2),
            ('Villa de Leyva',2),
            ('San Sebastián de Buenavista',2),
            ('Paz de Río',2),
            ('Hatillo de Loba',2),
            ('Sabanas de San Angel',2),
            ('Calamar',2),
            ('Río de Oro',2),
            ('San Pedro de Uraba',2),
            ('San José del Guaviare',2),
            ('Santa Rosa de Viterbo',2),
            ('Santander de Quilichao',2),
            ('Miraflores',2),
            ('Santafé de Antioquia',2),
            ('San Carlos de Guaroa',2),
            ('Palmar de Varela',2),
            ('Santa Rosa de Osos',2),
            ('San Andrés de Cuerquía',2),
            ('Valle de San Juan',2),
            ('San Vicente de Chucurí',2),
            ('San José de Miranda',2),
            ('Providencia',2),
            ('Santa Rosa de Cabal',2),
            ('Guayabal de Siquima',2),
            ('Belén de Los Andaquies',2),
            ('Paz de Ariporo',2),
            ('Santa Helena del Opón',2),
            ('San Pablo de Borbur',2),
            ('La Jagua del Pilar',2),
            ('La Jagua de Ibirico',2),
            ('San Luis de Sincé',2),
            ('San Luis de Gaceno',2),
            ('El Carmen de Bolívar',2),
            ('El Carmen de Atrato',2),
            ('San Juan de Betulia',2),
            ('Pijiño del Carmen',2),
            ('Vigía del Fuerte',2),
            ('San Martín de Loba',2),
            ('Altos del Rosario',2),
            ('Carmen de Apicala',2),
            ('San Antonio del Tequendama',2),
            ('Sabana de Torres',2),
            ('El Retorno',2),
            ('San José de Uré',2),
            ('San Pedro de Cartago',2),
            ('Campo de La Cruz',2),
            ('San Juan de Arama',2),
            ('San José de La Montaña',2),
            ('Cartagena del Chairá',2),
            ('San José del Palmar',2),
            ('Agua de Dios',2),
            ('San Jacinto del Cauca',2),
            ('San Agustín',2),
            ('El Tablón de Gómez',2),
            ('San Andrés',2),
            ('San José de Pare',2),
            ('Valle de Guamez',2),
            ('San Pablo de Borbur',2),
            ('Santiago de Tolú',2),
            ('Bogotá D.C.',2),
            ('Carmen de Carupa',2),
            ('Ciénaga de Oro',2),
            ('San Juan de Urabá',2),
            ('San Juan del Cesar',2),
            ('El Carmen de Chucurí',2),
            ('El Carmen de Viboral',2),
            ('Belén de Umbría',2),
            ('Belén de Bajira',2),
            ('Valle de San José',2),
            ('San Luis',2),
            ('San Miguel de Sema',2),
            ('San Antonio',2),
            ('San Benito',2),
            ('Vergara',2),
            ('San Carlos',2),
            ('Puerto Alegría',2),
            ('Hato',2),
            ('San Jacinto',2),
            ('San Sebastián',2),
            ('San Carlos',2),
            ('Tuta',2),
            ('Silos',2),
            ('Cácota',2),
            ('El Dovio',2),
            ('Toledo',2),
            ('Roldanillo',2),
            ('Mutiscua',2),
            ('Argelia',2),
            ('El Zulia',2),
            ('Salazar',2),
            ('Sevilla',2),
            ('Zarzal',2),
            ('Cucutilla',2),
            ('El Cerrito',2),
            ('Cartago',2),
            ('Caicedonia',2),
            ('Puerto Santander',2),
            ('Gramalote',2),
            ('El Cairo',2),
            ('El Tarra',2),
            ('La Unión',2),
            ('Restrepo',2),
            ('Teorama',2),
            ('Dagua',2),
            ('Arboledas',2),
            ('Guacarí',2),
            ('Lourdes',2),
            ('Ansermanuevo',2),
            ('Bochalema',2),
            ('Bugalagrande',2),
            ('Convención',2),
            ('Hacarí',2),
            ('La Victoria',2),
            ('Herrán',2),
            ('Ginebra',2),
            ('Yumbo',2),
            ('Obando',2),
            ('Tibú',2),
            ('San Cayetano',2),
            ('San Calixto',2),
            ('Bolívar',2),
            ('La Playa',2),
            ('Cali',2),
            ('San Pedro',2),
            ('Guadalajara de Buga',2),
            ('Chinácota',2),
            ('Ragonvalia',2),
            ('La Esperanza',2),
            ('Villa del Rosario',2),
            ('Chitagá',2),
            ('Calima',2),
            ('Sardinata',2),
            ('Andalucía',2),
            ('Pradera',2),
            ('Abrego',2),
            ('Los Patios',2),
            ('Ocaña',2),
            ('Bucarasica',2),
            ('Yotoco',2),
            ('Palmira',2),
            ('Riofrío',2),
            ('Santiago',2),
            ('Alcalá',2),
            ('Versalles',2),
            ('Labateca',2),
            ('Cachirá',2),
            ('Villa Caro',2),
            ('Durania',2),
            ('El Águila',2),
            ('Toro',2),
            ('Candelaria',2),
            ('La Cumbre',2),
            ('Ulloa',2),
            ('Trujillo',2),
            ('Vijes',2)
        ");
    }
}
